services:

#   nginx-certbot:
#     build: ./nginx-certbot
#     volumes:
#       - certbot_challenges:/var/www/certbot
#     ports:
#       - "80:80"

# # remove volumes and --keep-until-expiring from certbot command when want to create a new certificate and add it once certificate created (add --force-renewal instead if it presents an interactive screen)
#   certbot:
#     image: certbot/certbot
#     volumes:
#       - letsencrypt:/etc/letsencrypt
#       - certbot_challenges:/var/www/certbot
#     entrypoint: >
#       sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot 
#       --email nthbuddy123@gmail.com --agree-tos --no-eff-email 
#       --keep-until-expiring -d nth-backend.api.credenz.co.in && echo '✅ Certbot finished successfully!'"
#     depends_on:
#       nginx-certbot:
#         condition: service_started
  
#   shutdown-nginx-certbot:
#     image: alpine
#     depends_on:
#       certbot:
#         condition: service_completed_successfully
#     command: >
#       sh -c "echo 'Certbot finished, triggering nginx-certbot shutdown...' && 
#       sleep 2 && 
#       kill -TERM 1"
#     pid: "service:nginx-certbot"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nth
      POSTGRES_PASSWORD: nthDB@123
      POSTGRES_DB: nthdatabase
    ports:
      - "6969:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nth -d nthdatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports: 
      - "5789:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  admin:
    build:
      context: ./admin
      args:
        NEXT_PUBLIC_BACKUP_TOKEN: ${NEXT_PUBLIC_BACKUP_TOKEN}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports: 
      - "4788:4000"
    env_file:
      - .env
    depends_on:
      - postgres
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      backend:
        condition: service_started
      admin:
        condition: service_started
      # shutdown-nginx-certbot:
      #   condition: service_completed_successfully
    restart: always

volumes:
  postgres_data:
  letsencrypt:
  certbot_challenges:
